---
- hosts: nodes
  tasks:
  - name: Remove & Add Parametrs Loop
    lineinfile:
      path: /etc/default/grub
      state: present
      regexp: '(GRUB_CMDLINE_LINUX=\".*?){{ item.remove }}(.*)(?=\")'
      line: '\1\3{{ item.add }}"'
      backrefs: yes
    loop:
      - remove: '(\s*biosdevname=.)'
        add: ''
      - remove: '(\s*net\.ifnames=.)'
        add: ''
      - remove: '(\s?)'
        add: ''
      - remove: '()'
        add: ' biosdevname=0 net.ifnames=0'
  - name: Write GRUB Configuration File
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
...
